In [2]:
import pandas as pd
data=pd.read_csv("/home/simplon/Téléchargements/support de cours/Rafik/thanksgiving.csv",encoding='latin-1')
#data.head()
data.columns

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

Filtrer des données
• Utiliser la méthode Series.value_counts() pour afficher le décompte
du nombre de réponses pour chaque catégorie de la colonne 'Do you
celebrate Thanksgiving?'.
• Filtrer et garder toutes les lignes du dataframe data pour lesquelles la
réponse à la question 'Do you celebrate Thanksgiving?' est 'Yes'.
• Assigner ce nouveau dataframe à data et afficher le.

In [3]:
data['Do you celebrate Thanksgiving?'].value_counts()

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [4]:
data2=data[data['Do you celebrate Thanksgiving?']=='Yes']
data2

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1053,4335944082,Yes,Turkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,Yes,No,No,NaN,Rural,30 - 44,Female,"$100,000 to $124,999",Mountain
1054,4335943173,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Suburban,60+,Female,"$50,000 to $74,999",Pacific
1055,4335943060,Yes,Other (please specify),Duck,Baked,NaN,Rice-based,NaN,None,NaN,...,Yes,Yes,Yes,No,NaN,Urban,60+,Male,"$100,000 to $124,999",Pacific
1056,4335934708,Yes,Turkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,Yes,No,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1057,4335894916,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN

Exploration des repas de thanksgiving
• Utiliser la méthode Series.value_counts() pour afficher combien de fois chaque résultat apparaît pour la question et colonne 'What is typically the main dish at your Thanksgiving dinner?'.
• Afficher la colonne 'Do you typically have gravy?' pour les lignes du dataframe data pour lesquelles la colonne 'What is typically the main dish at your Thanksgiving dinner?' vaut 'Tofurkey' pour la dinde de tofu.
• Créer un filtre qui sélectionne seulement les lignes du dataframe data où 'What is typically the main dish at your Thanksgiving dinner?' vaut 'Tofurkey'
• Assigner le résultat à la variable tofurkey
• Afficher la colonne 'Do you typically have gravy?' de ce nouveau dataframe tofurkey

In [5]:
data['What is typically the main dish at your Thanksgiving dinner?'].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [6]:
data[data['What is typically the main dish at your Thanksgiving dinner?']=='Tofurkey']['Do you typically have gravy?']

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

Tendances des desserts pour Thanksgiving
• Créer un objet Series indiquant avec des booléens les valeurs de la colonne 'Which type
of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'
qui sont nulles. Assigner le résultat à la variable apple_isnull.
• Créer un objet Series indiquant avec des booléens les valeurs de la colonne 'Which type
of pie is typically served at your Thanksgiving dinner? Please select all that apply. -
Pumpkin' qui sont nulles. Assigner le résultat à la variable pumpkin_isnull.
• Créer un objet Series indiquant avec des booléens les valeurs de la colonne 'Which type
of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan'
qui sont nulles. Assigner le résultat à la variable pecan_isnull.
• Combiner ces 3 objets Series avec l'opérateur & et assigner le résultat à la variable pies.
• Afficher les valeurs uniques et combien de fois elles apparaissent dans la colonne de
pies.

In [7]:
apple_isnull=data2['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'].isnull()
#['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'].values
apple_isnull

0       False
1       False
2       False
3        True
4       False
        ...
1053     True
1054     True
1055    False
1056     True
1057     True
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple, Length: 980, dtype: bool

In [8]:
pumpkin_isnull=data2['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin'].isnull()
pumpkin_isnull

0        True
1       False
2       False
3       False
4       False
        ...
1053    False
1054    False
1055     True
1056     True
1057     True
Name: Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin, Length: 980, dtype: bool

In [9]:
pecan_isnull=data2['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan'].isnull()
print(type(pecan_isnull))

<class 'pandas.core.series.Series'>

In [10]:
pies=pecan_isnull&pumpkin_isnull&apple_isnull
pies.value_counts()

False    876
True     104
dtype: int64

Convertir l'âge en une valeur numérique
• Ecrire une fonction qui convertit une chaine de caractères en une valeur entière. Cela
permettra de convertir les valeurs de la colonne 'Age' en entiers. Cette fonction prendra
en paramètre une chaine de caractères (les valeurs actuelles de la colonne 'Age')
    • Utiliser la fonction isnull() pour vérifier si les valeurs sont nulles. Ajouter une condition if qui
    retourne 'None' si la valeur est nulle
    • Séparer les chaines de caractères en fonction de l'espace (' ') et extraire le premier élément de la
    liste résultante (méthode split())
    • Remplacer le caractère '+' dans le résultat avec une chaine de caractères vide en remplacement
    pour le supprimer (méthode replace())
    • utiliser int() pour convertir le résultat en entier
    • Retourner le résultat
• Utiliser la méthode Series.apply() pour appliquer la fonction à chaque valeur de la
colonne 'Age' du dataframe data.
    • Assigner le résultat à la nouvelle colonne int_age du dataframe data
• Appeler la méthode Series.describe() sur la colonne 'int_age' du dataframe data et
afficher le résultat.

In [44]:
import pandas as pd
def castint(s):
    if pd.isnull(s):
        return None
    else:
        return int(s.split()[0].replace('+',''))
data['int_age']=data2['Age'].apply(castint)
data['int_age'].describe()

count    947.000000
mean      40.089757
std       15.352014
min       18.000000
25%       30.000000
50%       45.000000
75%       60.000000
max       60.000000
Name: int_age, dtype: float64

Convertir les revenus en valeurs numériques
• Ecrire une fonction pour convertir les revenus en valeur unique de format entier.
    • Utiliser la fonction isnull() pour vérifier si la valeur est nulle. Si c'est le cas, retourner 'None'
    • Séparer la chaine de caractères en prenant l'espace comme délimiteur et extraire le premier
    élément de la liste résultante
    • Si le résultat vaut 'Prefer', retourner 'none'
    • Remplacer les caractères '$' et ',' par des chaines de caractères vides pour les supprimer
    • Utiliser int() pour convertir le résultat en entier
    • Retourner le résultat
• Utiliser la méthode Series.apply() pour appliquer la fonction précédente à chaque
valeur de la colonne 'How much total combined money did all members of your
HOUSEHOLD earn last year?' du dataframe data.
    • Assigner le résultat à la nouvelle colonne 'int_income' du dataframe data
• Appeler la méthode Series.describe() à la colonne int_income du dataframe data
et afficher le résultat.

In [46]:
def castincome(s):
    if pd.isnull(s):
        return None
    else :
        if s.split()[0] =='Prefer':
            return None
        else:
            return int(s.split()[0].replace('$','').replace(',',''))

data['int_income']=data2['How much total combined money did all members of your HOUSEHOLD earn last year?'].apply(castincome)
data['int_income'].describe()

count       829.000000
mean      75965.018094
std       59068.636748
min           0.000000
25%       25000.000000
50%       75000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

Corrélation entre distance et revenus
• Regarder de quelle manière les personnes gagnant moins de 150000
dollars voyagent.
    • Filtrer data en sélectionnant seulement les valeurs de 'int_income' inférieures
    à 150000
    • Sélectionner la colonne 'How far will you travel for Thanksgiving?' en prenant
    en compte le filtre
    • Utiliser la méthode value_counts() pour compter combien de fois chaque
    valeur apparaît dans la colonne
    • Afficher les résultats
• Faire de même avec les personnes gagnant plus de 150000 dollars.

In [41]:
print(data[data['int_income']<150000]['How far will you travel for Thanksgiving?'].value_counts())
print(data[data['int_income']>=150000]['How far will you travel for Thanksgiving?'].value_counts())

Thanksgiving is happening at my home--I won't travel at all                         281
Thanksgiving is local--it will take place in the town I live in                     203
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    150
Thanksgiving is out of town and far away--I have to drive several hours or fly       55
Name: How far will you travel for Thanksgiving?, dtype: int64
Thanksgiving is happening at my home--I won't travel at all                         66
Thanksgiving is local--it will take place in the town I live in                     34
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    25
Thanksgiving is out of town and far away--I have to drive several hours or fly      15
Name: How far will you travel for Thanksgiving?, dtype: int64

Lien entre passer Thanksgiving entre amis
avec l'âge et le revenu
• Générer un pivot de table montrant la moyenne d'âge des sondés
pour chaque catégorie des questions 'Have you ever tried to meet up
with hometown friends on Thanksgiving night?' et 'Have you ever
attended a "Friendsgiving?"'.
    • Appeler la méthode pivot_table() sur le dataframe data
    • Passer au paramètre 'index' la valeur 'Have you ever tried to meet up with
    hometown friends on Thanksgiving night?'
    • Passer au paramètre 'columns' la valeur 'Have you ever attended a
    "Friendsgiving?"'
    • Passer au paramètre 'values' la valeur 'int_age'
    • Afficher les résultats
• Faire de même pour les revenues avec ces 2 questions.ta

In [42]:
age_friends=data.pivot_table(index='Have you ever tried to meet up with hometown friends on Thanksgiving night?', columns ='Have you ever attended a "Friendsgiving?"', values='int_age')
print(age_friends)

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

In [43]:
income_friends=data.pivot_table(index='Have you ever tried to meet up with hometown friends on Thanksgiving night?', columns ='Have you ever attended a "Friendsgiving?"', values='int_income')
print(income_friends)

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842